version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./vendor:/var/www/html/vendor
            - ./node_modules:/var/www/html/node_modules
        networks:
            - laravel
        depends_on:
            - postgres

    webserver:
        image: nginx:alpine
        container_name: nginx_webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    postgres:
        image: postgres:16.4
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: formularios_offline
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD:
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:

volumes:
    postgres_data:
